
import type { ArtStyle, StyleFolder } from './types';

const BUCKET_URL = 'https://storage.googleapis.com/aistudio-red-team';

export const DEFAULT_FOLDERS: StyleFolder[] = [
  { id: 'fld_nature', name: 'THIÊN NHIÊN', name_en: 'NATURE' },
  { id: 'fld_sketch', name: 'PHÁC THẢO', name_en: 'SKETCH' },
  { id: 'fld_watercolor', name: 'MÀU NƯỚC', name_en: 'WATER COLOR' },
  { id: 'fld_oilpainting', name: 'SƠN DẦU', name_en: 'OIL PAINTING' },
  { id: 'fld_vietnam', name: 'VIỆT NAM', name_en: 'VIET NAM' },
  { id: 'fld_danhhoa', name: 'DANH HỌA', name_en: 'MASTERS' },
  { id: 'fld_hoathinh', name: 'HOẠT HÌNH', name_en: 'ANIMATION' },
  { id: 'fld_chinese', name: 'TRUNG HOA', name_en: 'CHINESE' },
  { id: 'fld_photo', name: 'NHIẾP ẢNH', name_en: 'PHOTO' },
  { id: 'fld_khac', name: 'KHÁC', name_en: 'OTHERS' },
  { id: 'fld_3d', name: '3D', name_en: '3D' },
  { id: 'fld_dieukhac', name: 'ĐIÊU KHẮC', name_en: 'SCULPTURE' }
];

export const ART_STYLES: ArtStyle[] = [
  {
    id: 'lacquer-lotus-vietnam',
    label: 'Vietnamese Lacquer Lotus',
    label_vi: 'Sơn mài Hoa Sen Việt',
    folderId: 'fld_nature',
    prompt: 'A traditional Vietnamese lacquer painting style focused on lotus flowers and cranes. Rich earthy tones, deep blacks, vibrant greens, and shimmering gold leaf accents. The surface is glossy and smooth with visible craquelure and layered textures typical of son mai art.',
    prompt_vi: 'Phong cách tranh sơn mài truyền thống Việt Nam tập trung vào hoa sen và chim hạc. Tông màu đất phong phú, màu đen sâu, màu xanh rực rỡ và các điểm nhấn lá vàng lấp lánh. Bề mặt bóng loáng và mịn màng với những vết nứt nẻ và các lớp kết cấu đặc trưng của nghệ thuật sơn mài.',
    thumbnail: `https://picsum.photos/seed/lotus/200/100`,
    preview: `https://picsum.photos/seed/lotus/600/600`,
    exampleImage: `https://picsum.photos/seed/lotus/200/100`
  },
  {
    id: 'ink-wash-bamboo',
    label: 'Traditional Ink Bamboo',
    label_vi: 'Trúc Thủy Mặc',
    folderId: 'fld_nature',
    prompt: 'Elegant oriental ink wash painting of bamboo branches. Expressive calligraphic brushstrokes, varying shades of black and grey ink on aged rice paper. Minimalist composition with a focus on flow, rhythm, and empty negative space.',
    prompt_vi: 'Tranh thủy mặc phương Đông thanh lịch vẽ cành trúc. Các nét cọ thư pháp biểu cảm, các sắc thái mực đen và xám khác nhau trên giấy xuyến chỉ cũ. Bố cục tối giản tập trung vào dòng chảy, nhịp điệu và không gian trống.',
    thumbnail: `https://picsum.photos/seed/bamboo/200/100`,
    preview: `https://picsum.photos/seed/bamboo/600/600`,
    exampleImage: `https://picsum.photos/seed/bamboo/200/100`
  },
  {
    id: 'vintage-botanical-art',
    label: 'Vintage Botanical Illustration',
    label_vi: 'Minh họa Thực vật Cổ điển',
    folderId: 'fld_nature',
    prompt: 'A classic 19th-century botanical scientific illustration. Highly detailed rendering of flowers and leaves with precise pen work and soft watercolor washes. Features technical notes, cross-sections of the plant, and a clean cream parchment background.',
    prompt_vi: 'Minh họa khoa học thực vật cổ điển thế kỷ 19. Thể hiện chi tiết hoa và lá với các nét bút chính xác và các mảng màu nước mềm mại. Có các ghi chú kỹ thuật, mặt cắt ngang của cây và nền giấy da màu kem sạch sẽ.',
    thumbnail: `https://picsum.photos/seed/botany/200/100`,
    preview: `https://picsum.photos/seed/botany/600/600`,
    exampleImage: `https://picsum.photos/seed/botany/200/100`
  },
  {
    id: 'majestic-pine-bonsai',
    label: 'Majestic Ancient Pine',
    label_vi: 'Tùng Cổ Thụ',
    folderId: 'fld_nature',
    prompt: 'An expressive oil painting of a majestic ancient pine tree (bonsai style). Rugged, textured bark, deep green needle clusters, and dramatic gnarled branches. High contrast lighting with a misty mountain background in the style of classical landscape masters.',
    prompt_vi: 'Tranh sơn dầu biểu cảm về một cây tùng cổ thụ hùng vĩ (phong cách bonsai). Vỏ cây gồ ghề, có kết cấu, những chùm kim xanh đậm và những cành cây vặn xoắn đầy kịch tính. Ánh sáng tương phản cao với nền núi sương mù theo phong cách của các bậc thầy phong cảnh cổ điển.',
    thumbnail: `https://picsum.photos/seed/pine/200/100`,
    preview: `https://picsum.photos/seed/pine/600/600`,
    exampleImage: `https://picsum.photos/seed/pine/200/100`
  },
  {
    id: 'wildflower-meadow-oil',
    label: 'Impressionist Floral Meadow',
    label_vi: 'Đồng Hoa Ấn Tượng',
    folderId: 'fld_nature',
    prompt: 'A vibrant impressionist painting of a field of wildflowers. Short, thick brushstrokes (impasto) and a brilliant palette of sun-drenched colors. The artwork captures the shifting light and movement of wind through petals and grass.',
    prompt_vi: 'Một bức tranh ấn tượng rực rỡ về cánh đồng hoa dại. Các nét cọ ngắn, dày (đắp nổi) và bảng màu rực rỡ của những màu sắc tràn ngập ánh nắng. Tác phẩm ghi lại ánh sáng thay đổi và chuyển động của gió qua những cánh hoa và ngọn cỏ.',
    thumbnail: `https://picsum.photos/seed/meadow/200/100`,
    preview: `https://picsum.photos/seed/meadow/600/600`,
    exampleImage: `https://picsum.photos/seed/meadow/200/100`
  },
  {
    id: 'high-key-studio',
    label: 'High-Key Professional Studio',
    label_vi: 'Studio High-Key Sáng trắng',
    folderId: 'fld_photo',
    prompt: 'Professional high-key studio photography. Bright, even lighting with minimal shadows. Pure white minimalist background. Clean, airy aesthetic with sharp focus and natural skin tones. High-end commercial look.',
    prompt_vi: 'Nhiếp ảnh studio chuyên nghiệp phong cách high-key. Ánh sáng sáng và đều với bóng đổ tối thiểu. Nền trắng tối giản tinh khiết. Thẩm mỹ sạch sẽ, thoáng đãng với tiêu cự sắc nét và tông màu da tự nhiên. Giao diện thương mại cao cấp.',
    thumbnail: `https://picsum.photos/seed/highkey/200/100`,
    preview: `https://picsum.photos/seed/highkey/600/600`,
    exampleImage: `https://picsum.photos/seed/highkey/200/100`
  },
  {
    id: 'teal-orange-cinematic',
    label: 'Teal & Orange Cinematic',
    label_vi: 'Điện ảnh Teal & Orange',
    folderId: 'fld_photo',
    prompt: 'Cinematic photography with a classic Teal and Orange color grade. Deep shadows with cool teal tones and warm, orange-hued highlights on skin and subjects. Moody, high-contrast atmospheric lighting like a modern Hollywood film.',
    prompt_vi: 'Nhiếp ảnh điện ảnh với phong cách phối màu Teal và Orange cổ điển. Bóng đổ sâu với tông màu xanh teal mát mẻ và vùng sáng tông màu cam ấm áp trên da và chủ thể. Ánh sáng bầu không khí u tối, độ tương phản cao như một bộ phim Hollywood hiện đại.',
    thumbnail: `https://picsum.photos/seed/tealorange/200/100`,
    preview: `https://picsum.photos/seed/tealorange/600/600`,
    exampleImage: `https://picsum.photos/seed/tealorange/200/100`
  },
  {
    id: 'polaroid-vintage-lofi',
    label: 'Vintage Polaroid Lo-Fi',
    label_vi: 'Ảnh Polaroid Cổ điển',
    folderId: 'fld_photo',
    prompt: 'Authentic vintage Polaroid photography aesthetic. Soft focus, slightly washed-out colors, and a warm nostalgic tint. Features characteristic film grain, light leaks, and the iconic square white border. Emotional, spontaneous lo-fi character.',
    prompt_vi: 'Thẩm mỹ nhiếp ảnh Polaroid cổ điển đích thực. Tiêu cự mềm, màu sắc hơi bạc màu và tông màu hoài cổ ấm áp. Đặc trưng bởi hạt phim, rò rỉ ánh sáng và viền trắng vuông biểu tượng. Đặc điểm lo-fi đầy cảm xúc và ngẫu hứng.',
    thumbnail: `https://picsum.photos/seed/polaroid/200/100`,
    preview: `https://picsum.photos/seed/polaroid/600/600`,
    exampleImage: `https://picsum.photos/seed/polaroid/200/100`
  },
  {
    id: 'dramatic-low-key-noir',
    label: 'Dramatic Low-Key Portrait',
    label_vi: 'Chân dung Low-Key Kịch tính',
    folderId: 'fld_photo',
    prompt: 'Dramatic low-key photography. Dark, moody atmosphere with heavy shadows and high-contrast Rembrandt lighting. Sharp highlights define the subject against a deep black background. Mysterious and sophisticated artistic look.',
    prompt_vi: 'Nhiếp ảnh low-key kịch tính. Bầu không khí tối, u uất với bóng đổ nặng và ánh sáng Rembrandt độ tương phản cao. Các vùng sáng sắc nét xác định chủ thể trên nền đen sâu thẳm. Giao diện nghệ thuật bí ẩn và tinh tế.',
    thumbnail: `https://picsum.photos/seed/lowkey/200/100`,
    preview: `https://picsum.photos/seed/lowkey/600/600`,
    exampleImage: `https://picsum.photos/seed/lowkey/200/100`
  },
  {
    id: 'editorial-fashion-studio',
    label: 'High-Fashion Editorial',
    label_vi: 'Thời trang Cao cấp',
    folderId: 'fld_photo',
    prompt: 'Professional high-fashion editorial photography. Sophisticated lighting with sharp focus on textures and fabric. High-end retouching aesthetic, dramatic shadows, and a polished magazine look like Vogue or Harper\'s Bazaar. Vibrant yet controlled colors.',
    prompt_vi: 'Nhiếp ảnh thời trang cao cấp chuyên nghiệp. Ánh sáng tinh tế với độ sắc nét cực cao vào kết cấu và chất liệu vải. Thẩm mỹ hậu kỳ cao cấp, bóng đổ kịch tính và vẻ ngoài trau chuốt của các tạp chí như Vogue hay Harper\'s Bazaar. Màu sắc rực rỡ nhưng được kiểm soát tốt.',
    thumbnail: `https://picsum.photos/seed/fashion-edit/200/100`,
    preview: `https://picsum.photos/seed/fashion-edit/600/600`,
    exampleImage: `https://picsum.photos/seed/fashion-edit/200/100`
  },
  {
    id: 'minimalist-muted-photo',
    label: 'Minimalist Muted',
    label_vi: 'Nhiếp ảnh Tối giản',
    folderId: 'fld_photo',
    prompt: 'Contemporary minimalist photography with a muted, desaturated color palette. Clean compositions, soft diffused light, and an emphasis on subtle tones. Aesthetic is calm, modern, and high-end artistic. Very low contrast between colors for a cohesive look.',
    prompt_vi: 'Nhiếp ảnh tối giản đương đại với bảng màu trầm, ít bão hòa. Bố cục sạch sẽ, ánh sáng khuếch tán mềm mại và nhấn mạnh vào các tông màu tinh tế. Thẩm mỹ bình tĩnh, hiện đại và mang tính nghệ thuật cao cấp. Độ tương phản màu sắc rất thấp tạo nên vẻ ngoài đồng nhất.',
    thumbnail: `https://picsum.photos/seed/minimal-photo/200/100`,
    preview: `https://picsum.photos/seed/minimal-photo/600/600`,
    exampleImage: `https://picsum.photos/seed/minimal-photo/200/100`
  },
  {
    id: 'fujifilm-classic-chrome',
    label: 'Fujifilm Classic Chrome',
    label_vi: 'Màu phim Fujifilm Retro',
    folderId: 'fld_photo',
    prompt: 'Analog photography style inspired by Fujifilm Classic Chrome film stock. Features deep, rich blacks, slightly greenish-blue shadows, and warm highlights. High documentary-style contrast with a nostalgic, organic film grain. Realistic skin tones with a vintage retro character.',
    prompt_vi: 'Phong cách nhiếp ảnh analog lấy cảm hứng từ dòng phim Fujifilm Classic Chrome. Đặc trưng bởi màu đen sâu, đậm, bóng đổ hơi xanh lục lam và vùng sáng ấm áp. Độ tương phản cao phong cách tài liệu với hạt phim hữu cơ hoài cổ. Tông màu da chân thực mang nét cổ điển retro.',
    thumbnail: `https://picsum.photos/seed/fujifilm/200/100`,
    preview: `https://picsum.photos/seed/fujifilm/600/600`,
    exampleImage: `https://picsum.photos/seed/fujifilm/200/100`
  },
  {
    id: 'vogue-red-editorial',
    label: 'Vogue Red Editorial',
    label_vi: 'Chân dung Vogue Đỏ',
    folderId: 'fld_photo',
    prompt: 'High-fashion editorial portrait in the style of a Vogue magazine cover. Dramatic red spotlighting with depth, sharp shadows. The background is a solid, vibrant crimson red. Elegant and sophisticated atmosphere with a cinematic, high-contrast look and professional studio lighting.',
    prompt_vi: 'Chân dung biên tập thời trang cao cấp theo phong cách bìa tạp chí Vogue. Ánh đèn spotlight đỏ kịch tính với bóng đổ sâu và sắc nét. Nền là màu đỏ thẫm rực rỡ và đồng nhất. Bầu không khí thanh lịch và tinh tế với giao diện điện ảnh, độ tương phản cao và ánh sáng studio chuyên nghiệp.',
    thumbnail: `https://picsum.photos/seed/vogue-red/200/100`,
    preview: `https://picsum.photos/seed/vogue-red/600/600`,
    exampleImage: `https://picsum.photos/seed/vogue-red/200/100`
  },
  {
    id: 'cinematic-film-noir',
    label: 'Cinematic Film Noir',
    label_vi: 'Phim điện ảnh Noir',
    folderId: 'fld_photo',
    prompt: 'A dramatic Cinematic Film Noir style photograph. High-contrast black and white with deep shadows and sharp highlights. Moody atmospheric lighting, silhouetted forms, and a gritty detective movie aesthetic from the 1940s. Shot on 35mm film with classic grainy texture.',
    prompt_vi: 'Một bức ảnh phong cách phim Noir kịch tính. Độ tương phản đen trắng cao với bóng đổ sâu và vùng sáng sắc nét. Ánh sáng bầu không khí u tối, các hình khối đổ bóng và thẩm mỹ phim thám tử gai góc từ những năm 1940. Chụp trên phim 35mm với kết cấu hạt cổ điển.',
    thumbnail: `https://picsum.photos/seed/noir/200/100`,
    preview: `https://picsum.photos/seed/noir/600/600`,
    exampleImage: `https://picsum.photos/seed/noir/200/100`
  },
  {
    id: 'vintage-kodak-film',
    label: 'Vintage Kodak Portra 400',
    label_vi: 'Phim Kodak Cổ điển',
    folderId: 'fld_photo',
    prompt: 'A warm, nostalgic photograph in the style of Kodak Portra 400 analog film. Features soft skin tones, natural warm sunlight, and subtle film grain. The colors are rich yet realistic with a slight golden-hour glow. Timeless and organic photography aesthetic with beautiful bokeh.',
    prompt_vi: 'Một bức ảnh ấm áp, hoài cổ theo phong cách phim analog Kodak Portra 400. Đặc trưng bởi tông màu da mềm mại, ánh nắng ấm áp tự nhiên và hạt phim nhẹ nhàng. Màu sắc phong phú nhưng chân thực với ánh sáng giờ vàng nhẹ nhàng. Thẩm mỹ nhiếp ảnh vượt thời gian và hữu cơ với hiệu ứng xóa phông đẹp mắt.',
    thumbnail: `https://picsum.photos/seed/kodak/200/100`,
    preview: `https://picsum.photos/seed/kodak/600/600`,
    exampleImage: `https://picsum.photos/seed/kodak/200/100`
  },
  {
    id: 'nat-geo-portrait',
    label: 'National Geographic Portrait',
    label_vi: 'Chân dung Nat-Geo',
    folderId: 'fld_photo',
    prompt: 'A stunning National Geographic style portrait. Sharp focus on the subject with extreme detail in skin texture and eyes. Natural, soft outdoor lighting. The composition is powerful and storytelling, capturing raw human emotion and cultural depth. Shallow depth of field with a beautifully blurred environmental background.',
    prompt_vi: 'Một bức chân dung phong cách National Geographic tuyệt đẹp. Độ sắc nét cao vào chủ thể với chi tiết cực độ về kết cấu da và đôi mắt. Ánh sáng ngoài trời tự nhiên, mềm mại. Bố cục mạnh mẽ và mang tính kể chuyện, ghi lại cảm xúc thô mộc của con người và chiều sâu văn hóa. Độ sâu trường ảnh nông với nền môi trường mờ ảo đẹp mắt.',
    thumbnail: `https://picsum.photos/seed/natgeo/200/100`,
    preview: `https://picsum.photos/seed/natgeo/600/600`,
    exampleImage: `https://picsum.photos/seed/natgeo/200/100`
  },
  {
    id: 'street-leica-monochrome',
    label: 'Street Leica Monochrome',
    label_vi: 'Nhiếp ảnh Đường phố Leica',
    folderId: 'fld_photo',
    prompt: 'Candid street photography in the legendary Leica monochrome style. Rich blacks and brilliant whites with a wide dynamic range. Sharp, fast lens aesthetic capturing a spontaneous moment in an urban setting. Timeless, journalistic feel with classic street photography composition.',
    prompt_vi: 'Nhiếp ảnh đường phố ngẫu hứng theo phong cách đơn sắc Leica huyền thoại. Màu đen phong phú và màu trắng rực rỡ với dải động rộng. Thẩm mỹ ống kính nhanh, sắc nét ghi lại khoảnh khắc tự phát trong bối cảnh đô thị. Cảm giác báo chí vượt thời gian với bố cục nhiếp ảnh đường phố cổ điển.',
    thumbnail: `https://picsum.photos/seed/leica/200/100`,
    preview: `https://picsum.photos/seed/leica/600/600`,
    exampleImage: `https://picsum.photos/seed/leica/200/100`
  },
  {
    id: 'dreamy-ethereal-glow',
    label: 'Dreamy Ethereal Glow',
    label_vi: 'Nhiếp ảnh Ánh sáng Huyền ảo',
    folderId: 'fld_photo',
    prompt: 'A dreamy and ethereal photography style. Soft-focus, high-key lighting that creates a glowing, celestial aura around the subject. Pastel color palette with diffused highlights. It feels like a romantic fantasy, with a misty atmospheric quality and gentle lens flares.',
    prompt_vi: 'Một phong cách nhiếp ảnh huyền ảo và mơ màng. Tiêu cự mềm, ánh sáng high-key tạo ra hào quang lung linh, thiên giới xung quanh chủ thể. Bảng màu pastel với các vùng sáng khuếch tán. Nó mang lại cảm giác như một thế giới thần tiên lãng mạn, với chất lượng không khí sương mù và các tia sáng ống kính nhẹ nhàng.',
    thumbnail: `https://picsum.photos/seed/ethereal/200/100`,
    preview: `https://picsum.photos/seed/ethereal/600/600`,
    exampleImage: `https://picsum.photos/seed/ethereal/200/100`
  },
  {
    id: 'cyber-neon-night',
    label: 'Cyber Neon Night',
    label_vi: 'Nhiếp ảnh Neon Đêm',
    folderId: 'fld_photo',
    prompt: 'Futuristic night photography with vibrant neon lights. Colors of magenta, cyan, and electric blue dominate the scene. Cinematic reflections on wet surfaces, high contrast, and a gritty cyberpunk urban atmosphere. Sharp details illuminated by artificial light sources.',
    prompt_vi: 'Nhiếp ảnh đêm tương lai với ánh đèn neon rực rỡ. Các màu hồng tím, xanh lam và xanh điện thống trị khung cảnh. Các phản chiếu điện ảnh trên bề mặt ướt, độ tương phản cao và bầu không khí đô thị cyberpunk gai góc. Các chi tiết sắc nét được chiếu sáng bởi các nguồn sáng nhân tạo.',
    thumbnail: `https://picsum.photos/seed/cyberneon/200/100`,
    preview: `https://picsum.photos/seed/cyberneon/600/600`,
    exampleImage: `https://picsum.photos/seed/cyberneon/200/100`
  },
  {
    id: 'classic-impasto-oil',
    label: 'Classic Impasto Oil',
    label_vi: 'Sơn dầu Đắp nổi (Impasto)',
    folderId: 'fld_oilpainting',
    prompt: 'A classic oil painting with heavy impasto technique. The portrait features thick, visible brushstrokes and palette knife textures that create a three-dimensional effect on the canvas. Rich, saturated colors with realistic highlights and deep shadows. The paint looks fresh and wet, with prominent ridges of oil color defining the facial features.',
    prompt_vi: 'Một bức tranh sơn dầu cổ điển với kỹ thuật đắp nổi (impasto) dày. Chân dung có các nét cọ dày, có thể nhìn thấy và kết cấu dao xúc tạo hiệu ứng ba chiều trên canvas. Màu sắc phong phú, bão hòa với những điểm sáng thực tế và bóng tối sâu. Lớp sơn trông như còn mới và ướt, với các đường gờ màu dầu nổi bật xác định các đường nét trên khuôn mặt.',
    thumbnail: `https://picsum.photos/seed/impasto/200/100`,
    preview: `https://picsum.photos/seed/impasto/600/600`,
    exampleImage: `https://picsum.photos/seed/impasto/200/100`
  },
  {
    id: 'renaissance-master-oil',
    label: 'Renaissance Master Oil',
    label_vi: 'Sơn dầu Phục hưng',
    folderId: 'fld_oilpainting',
    prompt: 'A formal portrait in the style of High Renaissance oil paintings. Features soft sfumato transitions, Chiaroscuro lighting with dramatic shadows, and a rich, dark atmospheric background. The surface has a fine craquelure texture of an aged museum masterpiece. Elegant, realistic skin tones and a timeless, dignified composition.',
    prompt_vi: 'Một bức chân dung trang trọng theo phong cách tranh sơn dầu thời kỳ Phục hưng đỉnh cao. Đặc trưng bởi các chuyển đổi sfumato mềm mại, ánh sáng Chiaroscuro với bóng đổ kịch tính và nền không khí tối, phong phú. Bề mặt có kết cấu nứt nẻ (craquelure) tinh xảo của một kiệt tác bảo tàng lâu đời. Tông màu da thanh lịch, chân thực và bố cục trang nghiêm, vượt thời gian.',
    thumbnail: `https://picsum.photos/seed/renaissance/200/100`,
    preview: `https://picsum.photos/seed/renaissance/600/600`,
    exampleImage: `https://picsum.photos/seed/renaissance/200/100`
  },
  {
    id: 'modern-palette-knife-portrait',
    label: 'Modern Palette Knife',
    label_vi: 'Sơn dầu Dao xúc Hiện đại',
    folderId: 'fld_oilpainting',
    prompt: 'A contemporary portrait created entirely with a palette knife. Bold, flat slabs of oil paint are applied to the canvas, creating a structural and semi-abstract look. High energy and vibrant, non-traditional color choices. The face is defined by the intersection of thick color planes, blending modern graphic sensibilities with traditional oil medium.',
    prompt_vi: 'Một bức chân dung đương đại được tạo ra hoàn toàn bằng dao xúc. Các mảng sơn dầu phẳng, táo bao được đắp lên canvas, tạo nên vẻ ngoài có cấu trúc và hơi trừu tượng. Năng lượng cao và lựa chọn màu sắc rực rỡ, không truyền thống. Khuôn mặt được xác định bởi sự giao thoa của các mảng màu dày, pha trộn cảm quan đồ họa hiện đại với chất liệu sơn dầu truyền thống.',
    thumbnail: `https://picsum.photos/seed/knife-oil/200/100`,
    preview: `https://picsum.photos/seed/knife-oil/600/600`,
    exampleImage: `https://picsum.photos/seed/knife-oil/200/100`
  },
  {
    id: 'architectural-blueprint-portrait',
    label: 'Architectural Blueprint Portrait',
    label_vi: 'Chân dung Bản vẽ Kỹ thuật',
    folderId: 'fld_khac',
    prompt: 'A unique blueprint style portrait. The image is rendered as a technical architectural drawing with white lines on a deep cyan background. It features precise drafting lines, grid patterns, and technical annotations, giving the face the appearance of a complex structural design or a construction blueprint. High contrast and professional engineering aesthetic.',
    prompt_vi: 'Một bức chân dung phong cách bản vẽ kỹ thuật độc đáo. Hình ảnh được thể hiện dưới dạng bản vẽ kiến trúc với các đường nét trắng trên nền xanh cyan đậm. Nó có các đường phác thảo chính xác, họa tiết lưới và các chú thích kỹ thuật, làm cho khuôn mặt trông giống như một thiết kế cấu trúc phức tạp hoặc một bản thiết kế xây dựng. Độ tương phản cao và thẩm mỹ kỹ thuật chuyên nghiệp.',
    thumbnail: `https://picsum.photos/seed/blueprint/200/100`,
    preview: `https://picsum.photos/seed/blueprint/600/600`,
    exampleImage: `https://picsum.photos/seed/blueprint/200/100`
  },
  {
    id: 'planar-head-study',
    label: 'Planar Head Study',
    label_vi: 'Nghiên cứu Diện mảng',
    folderId: 'fld_dieukhac',
    prompt: 'A professional planar head study, characterized by simplified geometric planes that define the structure, volume, and lighting of the face. It has a sculptural, architectural quality with sharp edges between planes and a monochromatic grey palette to emphasize form over surface detail. High contrast lighting that casts sharp shadows across the geometric facets.',
    prompt_vi: 'Một nghiên cứu diện mảng chuyên nghiệp, được đặc trưng bởi các mặt phẳng hình học đơn giản hóa xác định cấu trúc, khối lượng và ánh sáng của khuôn mặt. Nó mang chất lượng điêu khắc, kiến trúc với các cạnh sắc nét giữa các mặt phẳng và bảng màu xám đơn sắc để nhấn mạnh hình khối hơn chi tiết bề mặt. Ánh sáng độ tương phản cao đổ bóng sắc nét trên các mảng khối hình học.',
    thumbnail: `https://picsum.photos/seed/planar/200/100`,
    preview: `https://picsum.photos/seed/planar/600/600`,
    exampleImage: `https://picsum.photos/seed/planar/200/100`
  },
  {
    id: 'architectural-vector-portrait',
    label: 'Architectural Vector Portrait',
    label_vi: 'Chân dung Đồ họa Hình khối',
    folderId: 'fld_khac',
    prompt: 'A sophisticated graphic vector portrait with an architectural block aesthetic. The style uses flat, overlapping geometric shapes and sharp-edged color planes to define the face. It features a muted, earthy color palette with creams, tans, and browns. Lighting is represented through distinct posterized layers that emphasize the underlying facial structure and volume. Clean lines, minimalist details, and a modern professional graphic design feel.',
    prompt_vi: 'Một bức chân dung đồ họa vector tinh tế với thẩm mỹ hình khối kiến trúc. Phong cách này sử dụng các hình dạng hình học phẳng, chồng lên nhau và các mặt phẳng màu sắc sắc nét để xác định khuôn mặt. Nó có bảng màu đất trầm với các tông màu kem, nâu và rám nắng. Ánh sáng được thể hiện qua các lớp màu sắc rõ rệt giúp nhấn mạnh cấu trúc và khối lượng khuôn mặt. Đường nét sạch sẽ, chi tiết tối giản và mang lại cảm giác thiết kế đồ họa chuyên nghiệp hiện đại.',
    thumbnail: `https://picsum.photos/seed/vector-arch/200/100`,
    preview: `https://picsum.photos/seed/vector-arch/600/600`,
    exampleImage: `https://picsum.photos/seed/vector-arch/200/100`
  },
  {
    id: 'gestural-ink-figure',
    label: 'Gestural Ink Figure',
    label_vi: 'Phác thảo Hình họa Phóng khoáng',
    folderId: 'fld_sketch',
    prompt: 'A raw and expressive gestural ink drawing. Bold, rapid black ink strokes capture the essence of movement and human form with minimalist precision. The style is characterized by energetic, confident lines, purposeful splatters, and high contrast against a plain cream-white background. It feels like a spontaneous artist\'s sketchbook entry, emphasizing rhythm and action over anatomical perfection.',
    prompt_vi: 'Một bức vẽ mực đầy biểu cảm và thô mộc. Các nét mực đen táo bạo, nhanh chóng nắm bắt bản chất của chuyển động và hình thể con người với độ chính xác tối giản. Phong cách được đặc trưng bởi các đường nét tràn đầy năng lượng, tự tin và độ tương phản cao trên nền trắng kem đơn giản. Nó mang lại cảm giác như một trang nhật ký nghệ thuật ngẫu hứng, nhấn mạnh nhịp điệu và hành động hơn là sự hoàn hảo về giải phẫu.',
    thumbnail: `https://picsum.photos/seed/gestural/200/100`,
    preview: `https://picsum.photos/seed/gestural/600/600`,
    exampleImage: `https://picsum.photos/seed/gestural/200/100`
  },
  {
    id: 'calligraphic-brush-sketch',
    label: 'Calligraphic Brush Sketch',
    label_vi: 'Phác thảo Nét cọ Thư pháp',
    folderId: 'fld_sketch',
    prompt: 'A minimalist and expressive calligraphic ink drawing. The style is defined by thick, bold, and fluid black brushstrokes on a stark white background. It uses varying line weights and "dry brush" textures to suggest form with elegance and raw energy. No shading or fine details, focusing entirely on the dynamic power and flow of the single brush strokes.',
    prompt_vi: 'Một bức vẽ mực tàu thư pháp tối giản và biểu cảm. Phong cách được định nghĩa bởi những nét cọ đen dày, táo bạo và uyển chuyển trên nền trắng tinh khôi. Nó sử dụng các độ dày đường nét khác nhau và kết cấu "cọ khô" để gợi ý hình dạng với sự thanh lịch và năng lượng thô mộc. Không tô bóng hay chi tiết rườm rà, tập trung hoàn toàn vào sức mạnh năng động và dòng chảy của từng nét cọ đơn lẻ.',
    thumbnail: `https://picsum.photos/seed/calligraphy/200/100`,
    preview: `https://picsum.photos/seed/calligraphy/600/600`,
    exampleImage: `https://picsum.photos/seed/calligraphy/200/100`
  },
  {
    id: 'minimalist-contour-drawing',
    label: 'Minimalist Contour Drawing',
    label_vi: 'Phác thảo Nét thanh Tú',
    folderId: 'fld_sketch',
    prompt: 'A minimalist and elegant contour line drawing. The style features extremely thin, precise, and fluid black ink lines on a clean, stark white background. Focus on capturing silhouettes and delicate features with minimal strokes. No shading or textures, emphasizing pure line work and elegant negative space.',
    prompt_vi: 'Một bức vẽ nét viền tối giản và thanh lịch. Phong cách có các đường mực đen cực kỳ mỏng, chính xác và uyển chuyển trên nền trắng tinh khiết. Tập trung vào việc nắm bắt hình bóng và các đặc điểm tinh tế với những nét vẽ tối thiểu. Không có bóng hoặc kết cấu, nhấn mạnh vào đường nét thuần túy và không gian âm thanh lịch.',
    thumbnail: `https://picsum.photos/seed/minimal-contour/200/100`,
    preview: `https://picsum.photos/seed/minimal-contour/600/600`,
    exampleImage: `https://picsum.photos/seed/minimal-contour/200/100`
  },
  {
    id: 'scribble-gestural-sketch',
    label: 'Scribble Gestural Sketch',
    label_vi: 'Phác thảo Nét rối',
    folderId: 'fld_sketch',
    prompt: 'A raw, energetic scribble ink drawing. The style is characterized by loose, chaotic yet purposeful black ink lines on a clean white background. It features spontaneous gestural strokes, messy hatching, and exaggerated proportions that create a sense of movement and raw emotion. High contrast with zero shading other than the density of the lines themselves.',
    prompt_vi: 'Một bức vẽ mực theo phong cách nét rối đầy thô mộc và năng lượng. Phong cách được đặc trưng bởi các đường mực đen lỏng lẻo, hỗn loạn nhưng có mục đích trên nền trắng sạch. Nó có các nét vẽ cử chỉ tự phát, gạch chéo lộn xộn và tỷ lệ phóng đại tạo ra cảm giác chuyển động và cảm xúc thô. Độ tương phản cao with việc không tô bóng ngoài mật độ của chính các đường nét.',
    thumbnail: `https://picsum.photos/seed/scribble/200/100`,
    preview: `https://picsum.photos/seed/scribble/600/600`,
    exampleImage: `https://picsum.photos/seed/scribble/200/100`
  },
  {
    id: 'fine-line-pencil-study',
    label: 'Fine Line Pencil Study',
    label_vi: 'Phác thảo chì nét thanh',
    folderId: 'fld_sketch',
    prompt: 'A delicate and precise fine line pencil study of a male profile. The artwork features crisp, thin graphite lines, detailed facial features, and expressive hair textures. Light hatching and cross-hatching provide subtle depth and shadow, giving it the appearance of an artist\'s sketchbook entry on clean paper.',
    prompt_vi: 'Một bản phác thảo chì nét thanh tinh tế và chính xác về góc nghiêng của nam giới. Tác phẩm có các đường nét graphite sắc sảo, mỏng, các chi tiết khuôn mặt chi tiết và kết cấu tóc biểu cảm. Các nét gạch và gạch chéo nhẹ tạo ra chiều sâu và bóng đổ tinh tế, mang lại vẻ ngoài như một trang nhật ký nghệ thuật trên giấy sạch.',
    thumbnail: `https://picsum.photos/seed/pencil-study/200/100`,
    preview: `https://picsum.photos/seed/pencil-study/600/600`,
    exampleImage: `https://picsum.photos/seed/pencil-study/200/100`
  },
  {
    id: '6b-pencil-crosshatch',
    label: '6B Pencil Crosshatch',
    label_vi: 'Phác thảo chì 6B',
    folderId: 'fld_sketch',
    prompt: 'A detailed and expressive sketch created with a soft 6B pencil. The shading and tonal values are built up through multiple layers of dense, multi-directional cross-hatching, creating a rich texture and a wide range of shadows and light.',
    prompt_vi: 'Một bản phác thảo chi tiết và biểu cảm được tạo bằng bút chì 6B mềm. Việc tô bóng và các giá trị tông màu được tạo nên qua nhiều lớp gạch chéo dày đặc, đa hướng, tạo ra một kết cấu phong phú và dải bóng tối và ánh sáng rộng.',
    thumbnail: `${BUCKET_URL}/thumbnails/6b-pencil-crosshatch.webp`,
    preview: `${BUCKET_URL}/previews/6b-pencil-crosshatch.webp`,
    exampleImage: `https://picsum.photos/seed/6b-pencil-crosshatch/200/100`
  },
  {
    id: 'abstract-art',
    label: 'Abstract Art',
    label_vi: 'Nghệ thuật Trừu tượng',
    folderId: 'fld_khac',
    prompt: 'A dynamic and expressive abstract artwork. Focus on a composition of bold, interlocking geometric shapes and a vibrant, high-contrast color palette to create a sense of energy and movement.',
    prompt_vi: 'Một tác phẩm nghệ thuật trừu tượng năng động và biểu cảm. Tập trung vào bố cục của các hình dạng hình học táo bạo, lồng vào nhau và bảng màu rực rỡ, tương phản cao để tạo cảm giác năng lượng và chuyển động.',
    thumbnail: `${BUCKET_URL}/thumbnails/abstract-art.webp`,
    preview: `${BUCKET_URL}/previews/abstract-art.webp`,
    exampleImage: `https://picsum.photos/seed/abstract-art/200/100`
  },
  {
    id: 'anatomical-ink-sketch',
    label: 'Anatomical Ink Sketch',
    label_vi: 'Phác thảo Giải phẫu',
    folderId: 'fld_sketch',
    prompt: 'A dynamic anatomical ink sketch, in the style of an artist\'s study. The drawing should feature expressive, confident linework that defines the form and musculature of the subject. Include visible red construction lines and geometric guides to emphasize the underlying structure and proportions, giving it a technical, analytical feel while retaining a sense of energy and movement.',
    prompt_vi: 'Một bản phác thảo mực giải phẫu năng động, theo phong cách nghiên cứu của một nghệ sĩ. Bức vẽ phải có những đường nét biểu cảm, tự tin xác định hình dạng và cơ bắp của đối tượng. Bao gồm các đường dựng màu đỏ và các hướng dẫn hình học có thể nhìn thấy để nhấn mạnh cấu trúc và tỷ lệ cơ bản, mang lại cảm giác kỹ thuật, phân tích trong khi vẫn giữ được cảm giác năng lượng và chuyển động.',
    thumbnail: `${BUCKET_URL}/thumbnails/anatomical-ink-sketch.webp`,
    preview: `${BUCKET_URL}/previews/anatomical-ink-sketch.webp`,
    exampleImage: `https://picsum.photos/seed/anatomical-ink-sketch/200/100`
  },
  {
    id: 'anime',
    label: 'Anime',
    label_vi: 'Hoạt hình Nhật Bản',
    folderId: 'fld_hoathinh',
    prompt: 'a vibrant anime style artwork with cel shading, sharp lines, and expressive characters.',
    prompt_vi: 'một tác phẩm nghệ thuật theo phong cách anime rực rỡ với tô bóng cel, các đường nét sắc sảo và các nhân vật biểu cảm.',
    thumbnail: `${BUCKET_URL}/thumbnails/anime.webp`,
    preview: `${BUCKET_URL}/previews/anime.webp`,
    exampleImage: `https://picsum.photos/seed/anime/200/100`
  },
  {
    id: 'iron-pen-sketch-blue',
    label: 'Iron Pen Sketch (Blue)',
    label_vi: 'Bút sắt Mực xanh',
    folderId: 'fld_sketch',
    prompt: 'an intricate iron pen sketch using blue ink, characterized by sharp, deliberate lines and cross-hatching for depth and shadow.',
    prompt_vi: 'một bản phác thảo bút sắt phức tạp bằng mực xanh, đặc trưng bởi các đường nét sắc sảo, có chủ ý và gạch chéo để tạo chiều sâu và bóng tối.',
    thumbnail: `${BUCKET_URL}/thumbnails/blue-ink-pen.webp`,
    preview: `${BUCKET_URL}/previews/blue-ink-pen.webp`,
    exampleImage: `https://picsum.photos/seed/iron-pen-sketch-blue/200/100`
  },
  {
    id: 'bold-pencil-crosshatch',
    label: 'Bold Pencil Crosshatch',
    label_vi: 'Chì đậm Gạch chéo',
    folderId: 'fld_sketch',
    prompt: 'A bold pencil sketch characterized by thick, expressive lines. Shading and depth are created using prominent multi-directional cross-hatching techniques, giving the artwork a textured and dynamic feel.',
    prompt_vi: 'Một bản phác thảo chì táo bạo đặc trưng bởi các đường nét dày, biểu cảm. Bóng và chiều sâu được tạo ra bằng cách sử dụng các kỹ thuật gạch chéo đa hướng nổi bật, mang lại cho tác phẩm nghệ thuật một cảm giác có kết cấu và năng động.',
    thumbnail: `${BUCKET_URL}/thumbnails/bold-pencil-crosshatch.webp`,
    preview: `${BUCKET_URL}/previews/bold-pencil-crosshatch.webp`,
    exampleImage: `https://picsum.photos/seed/bold-pencil-crosshatch/200/100`
  },
  {
    id: 'bold-pencil-sketch',
    label: 'Bold Pencil Sketch',
    label_vi: 'Phác thảo Chì đậm',
    folderId: 'fld_sketch',
    prompt: 'a detailed pencil sketch with thick, bold, and expressive lines and heavy shading, creating a dramatic and high-contrast look.',
    prompt_vi: 'một bản phác thảo chì chi tiết với các đường nét dày, đậm và biểu cảm cùng với việc tô bóng đậm, tạo ra một giao diện đầy kịch tính và có độ tương phản cao.',
    thumbnail: `${BUCKET_URL}/thumbnails/bold-pencil-sketch.webp`,
    preview: `${BUCKET_URL}/previews/bold-pencil-sketch.webp`,
    exampleImage: `https://picsum.photos/seed/bold-pencil-sketch/200/100`
  },
  {
    id: 'caricature',
    label: 'Caricature',
    label_vi: 'Biếm họa',
    folderId: 'fld_khac',
    prompt: 'a caricature drawing with exaggerated features.',
    prompt_vi: 'một bức tranh biếm họa với các đặc điểm được phóng đại.',
    thumbnail: `${BUCKET_URL}/thumbnails/caricature.webp`,
    preview: `${BUCKET_URL}/previews/caricature.webp`,
    exampleImage: `https://picsum.photos/seed/caricature/200/100`
  },
  {
    id: 'charcoal-sketch',
    label: 'Charcoal Sketch',
    label_vi: 'Phác thảo Than củi',
    folderId: 'fld_sketch',
    prompt: 'a charcoal sketch with a smudged, grainy texture and a wide tonal range, capturing both deep blacks and subtle grays.',
    prompt_vi: 'một bản phác thảo than củi với kết cấu nhòe, sần sùi và dải tông màu rộng, ghi lại cả màu đen sâu và màu xám tinh tế.',
    thumbnail: `${BUCKET_URL}/thumbnails/charcoal-sketch.webp`,
    preview: `${BUCKET_URL}/previews/charcoal-sketch.webp`,
    exampleImage: `https://picsum.photos/seed/charcoal-sketch/200/100`
  },
  {
    id: 'chinese-ink-wash',
    label: 'Chinese Ink Wash',
    label_vi: 'Thủy mặc Trung Hoa',
    folderId: 'fld_chinese',
    prompt: 'A traditional Chinese ink wash painting (Shanshui hua). The style should feature expressive, calligraphic brushstrokes, a focus on mountainous landscapes, water elements, and atmospheric perspective. Use varying ink tones to create depth and mood, with an emphasis on minimalism, balance, and the beauty of nature.',
    prompt_vi: 'Một bức tranh thủy mặc truyền thống của Trung Quốc (Sơn thủy họa). Phong cách cần có những nét cọ thư pháp biểu cảm, tập trung vào phong cảnh núi non, các yếu tố nước và phối cảnh không khí. Sử dụng các tông màu mực khác nhau để tạo chiều sâu và tâm trạng, với sự nhấn mạnh vào sự tối giản, cân bằng và vẻ đẹp của thiên nhiên.',
    thumbnail: `${BUCKET_URL}/thumbnails/chinese-ink-wash.webp`,
    preview: `${BUCKET_URL}/previews/chinese-ink-wash.webp`,
    exampleImage: `https://picsum.photos/seed/chinese-ink-wash/200/100`
  },
  {
    id: 'colorful-brushwork',
    label: 'Colorful Brushwork',
    label_vi: 'Nét cọ Đa sắc',
    folderId: 'fld_oilpainting',
    prompt: 'A painting with a textured, painterly feel, characterized by visible, blocky, and expressive brushstrokes. The style uses a vibrant and rich color palette to create depth and raw texture.',
    prompt_vi: 'Một bức tranh có cảm giác họa sĩ, kết cấu, đặc trưng bởi các nét cọ có thể nhìn thấy, khối và biểu cảm. Phong cách sử dụng bảng màu rực rỡ và phong phú để tạo chiều sâu và kết cấu thô.',
    thumbnail: `${BUCKET_URL}/thumbnails/colorful-brushwork.webp`,
    preview: `${BUCKET_URL}/previews/colorful-brushwork.webp`,
    exampleImage: `https://picsum.photos/seed/colorful-brushwork/200/100`
  },
  {
    id: 'continuous-line-portrait',
    label: 'Continuous Line Portrait',
    label_vi: 'Chân dung Nét liền',
    folderId: 'fld_sketch',
    prompt: 'A minimalist continuous line portrait, where the subject is rendered using a single, unbroken, and fluid line. The style focuses on capturing the essential features and form with elegance and simplicity.',
    prompt_vi: 'Một bức chân dung đường nét liên tục tối giản, trong đó đối tượng được thể hiện bằng một đường duy nhất, không đứt đoạn và uyển chuyển. Phong cách tập trung vào việc nắm bắt các đặc điểm và hình thức thiết yếu với sự thanh lịch và đơn giản.',
    thumbnail: `${BUCKET_URL}/thumbnails/continuous-line-portrait.webp`,
    preview: `${BUCKET_URL}/previews/continuous-line-portrait.webp`,
    exampleImage: `https://picsum.photos/seed/continuous-line-portrait/200/100`
  },
  {
    id: 'crystal-object',
    label: 'Crystal Object',
    label_vi: 'Vật thể Pha lê',
    folderId: 'fld_3d',
    prompt: 'Transform the subject into a delicate and intricate sculpture made of shimmering, transparent crystal. The style should capture the play of light, with clear reflections and refractions, giving it an ethereal and magical quality.',
    prompt_vi: 'Biến đổi chủ thể thành một tác phẩm điêu khắc tinh xảo và tinh tế làm từ pha lê trong suốt, lung linh. Phong cách này phải nắm bắt được sự chơi đùa của ánh sáng, với các phản xạ và khúc xạ rõ ràng, mang lại cho nó một chất lượng thanh tao và huyền diệu.',
    thumbnail: `${BUCKET_URL}/thumbnails/crystal-object.webp`,
    preview: `${BUCKET_URL}/previews/crystal-object.webp`,
    exampleImage: `https://picsum.photos/seed/crystal-object/200/100`
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    label_vi: 'Cyberpunk',
    folderId: 'fld_photo',
    prompt: 'a futuristic cyberpunk cityscape with neon lights, high-tech elements, and a gritty atmosphere.',
    prompt_vi: 'một cảnh quan thành phố cyberpunk tương lai với đèn neon, các yếu tố công nghệ cao và một bầu không khí gai góc.',
    thumbnail: `${BUCKET_URL}/thumbnails/cyberpunk.webp`,
    preview: `${BUCKET_URL}/previews/cyberpunk.webp`,
    exampleImage: `https://picsum.photos/seed/cyberpunk/200/100`
  },
  {
    id: 'detailed-bronze-sculpture',
    label: 'Detailed Bronze Sculpture',
    label_vi: 'Điêu khắc Đồng chi tiết',
    folderId: 'fld_dieukhac',
    prompt: 'Transform the subject into a hyper-realistic and intricately detailed bronze sculpture. The style should capture the fine textures of aged metal, the dramatic interplay of light and shadow across the form, and the realistic definition of musculature and drapery. The final image should have the weight and gravitas of a classical masterpiece.',
    prompt_vi: 'Biến đổi chủ thể thành một tác phẩm điêu khắc bằng đồng siêu thực và chi tiết tinh xảo. Phong cách này phải nắm bắt được kết cấu tinh xảo của kim loại lâu năm, sự tương tác đầy kịch tính của ánh sáng và bóng tối trên hình dạng, và sự xác định thực tế của cơ bắp và nếp vải. Hình ảnh cuối cùng phải có sức nặng và sự trang trọng của một kiệt tác cổ điển.',
    thumbnail: `${BUCKET_URL}/thumbnails/detailed-bronze-sculpture.webp`,
    preview: `${BUCKET_URL}/previews/detailed-bronze-sculpture.webp`,
    exampleImage: `https://picsum.photos/seed/detailed-bronze-sculpture/200/100`
  },
  {
    id: 'dynamic-watercolor-sketch',
    label: 'Dynamic Watercolor Sketch',
    label_vi: 'Phác thảo Màu nước Năng động',
    folderId: 'fld_watercolor',
    prompt: 'An energetic and dynamic watercolor sketch, featuring loose, expressive ink linework combined with vibrant, playful watercolor splashes. The style should convey a sense of joy and movement, with a clean, modern feel, emphasizing expressive characters and a slightly exaggerated, illustrative quality.',
    prompt_vi: 'Một bản phác thảo màu nước tràn đầy năng lượng và năng động, có các đường mực lỏng lẻo, biểu cảm kết hợp với các mảng màu nước rực rỡ, vui tươi. Phong cách phải truyền tải cảm giác vui vẻ và chuyển động, với cảm giác sạch sẽ, hiện đại, nhấn mạnh các nhân vật biểu cảm và chất lượng minh họa hơi phóng đại.',
    thumbnail: `${BUCKET_URL}/thumbnails/dynamic-watercolor-sketch.webp`,
    preview: `${BUCKET_URL}/previews/dynamic-watercolor-sketch.webp`,
    exampleImage: `https://picsum.photos/seed/dynamic-watercolor-sketch/200/100`
  },
  {
    id: 'ethereal-watercolor',
    label: 'Ethereal Watercolor',
    label_vi: 'Màu nước Thanh tao',
    folderId: 'fld_watercolor',
    prompt: 'An ethereal watercolor portrait. The style should feature soft, blended washes of color creating a luminous, almost dreamlike quality. Emphasize a delicate interplay of light and shadow, retaining a sense of realism while embracing the fluid and expressive nature of the watercolor medium.',
    prompt_vi: 'Một bức chân dung màu nước thanh tao. Phong cách nên có các mảng màu mềm mại, hòa quyện tạo ra chất lượng sáng, gần như mơ mộng. Nhấn mạnh sự tương tác tinh tế của ánh sáng và bóng tối, giữ lại cảm giác chân thực trong khi nắm bắt bản chất lỏng và biểu cảm của phương tiện màu nước.',
    thumbnail: `${BUCKET_URL}/thumbnails/ethereal-watercolor.webp`,
    preview: `${BUCKET_URL}/previews/ethereal-watercolor.webp`,
    exampleImage: `https://picsum.photos/seed/ethereal-watercolor/200/100`
  },
  {
    id: 'expressive-watercolor-portrait',
    label: 'Expressive Watercolor Portrait',
    label_vi: 'Chân dung Màu nước Biểu cảm',
    folderId: 'fld_watercolor',
    prompt: 'An expressive and detailed watercolor portrait. Focus on capturing deep character and emotion. Use a realistic yet painterly approach, with visible brushstrokes and a rich, textured application of paint. Emphasize the interplay of light and shadow to create depth and volume. The color palette should be earthy and natural, with nuanced skin tones.',
    prompt_vi: 'Một bức chân dung màu nước biểu cảm và chi tiết. Tập trung vào việc nắm bắt tính cách và cảm xúc sâu sắc. Sử dụng phương pháp tiếp cận thực tế nhưng mang tính hội họa, với các nét cọ có thể nhìn thấy và ứng dụng sơn phong phú, có kết cấu. Nhấn mạnh sự tương tác của ánh sáng và bóng tối để tạo chiều sâu và khối lượng. Bảng màu nên là màu đất và tự nhiên, với tông màu da đa sắc thái.',
    thumbnail: `${BUCKET_URL}/thumbnails/expressive-watercolor-portrait.webp`,
    preview: `${BUCKET_URL}/previews/expressive-watercolor-portrait.webp`,
    exampleImage: `https://picsum.photos/seed/expressive-watercolor-portrait/200/100`
  },
  {
    id: 'fashion-watercolor-sketch',
    label: 'Fashion Watercolor Sketch',
    label_vi: 'Minh họa Thời trang Màu nước',
    folderId: 'fld_watercolor',
    prompt: 'A fashion illustration sketch combining clean, defined lines for the subject with loose, expressive watercolor splashes and drips in the background. The style should be elegant and modern, with a focus on form and a minimalist yet vibrant color palette.',
    prompt_vi: 'Một bản phác thảo minh họa thời trang kết hợp các đường nét sạch sẽ, rõ ràng cho chủ thể với các mảng màu nước và giọt màu lỏng lẻo, biểu cảm ở hậu cảnh. Phong cách phải thanh lịch và hiện đại, tập trung vào hình thức và bảng màu tối giản nhưng rực rỡ.',
    thumbnail: `${BUCKET_URL}/thumbnails/fashion-watercolor-sketch.webp`,
    preview: `${BUCKET_URL}/previews/fashion-watercolor-sketch.webp`,
    exampleImage: `https://picsum.photos/seed/fashion-watercolor-sketch/200/100`
  },
  {
    id: 'gouache-painting',
    label: 'Gouache Painting',
    label_vi: 'Tranh màu Bột (Gouache)',
    folderId: 'fld_watercolor',
    prompt: 'A vibrant and detailed painting in the style of gouache. The artwork should have an opaque, multiple finish with distinct, solid layers of color and fine details. The colors should be rich and saturated, capturing the characteristic chalky yet bold look of gouache.',
    prompt_vi: 'Một bức tranh rực rỡ và chi tiết theo phong cách gouache. Tác phẩm nghệ thuật phải có bề mặt mờ, đục với các lớp màu đặc, riêng biệt và các chi tiết tinh xảo. Màu sắc phải đậm và bão hòa, nắm bắt được vẻ ngoài đặc trưng của gouache vừa có chất phấn vừa táo bạo.',
    thumbnail: `${BUCKET_URL}/thumbnails/gouache-painting.webp`,
    preview: `${BUCKET_URL}/previews/gouache-painting.webp`,
    exampleImage: `https://picsum.photos/seed/gouache-painting/200/100`
  },
  {
    id: 'impressionism',
    label: 'Impressionism',
    label_vi: 'Trường phái Ấn tượng',
    folderId: 'fld_danhhoa',
    prompt: 'an impressionist painting with visible, short brushstrokes, an emphasis on the accurate depiction of light and its changing qualities, and a vibrant color palette.',
    prompt_vi: 'một bức tranh theo trường phái ấn tượng với các nét cọ ngắn, có thể nhìn thấy, nhấn mạnh vào việc mô tả chính xác ánh sáng và các phẩm chất thay đổi của nó, và một bảng màu rực rỡ.',
    thumbnail: `${BUCKET_URL}/thumbnails/impressionism.webp`,
    preview: `${BUCKET_URL}/previews/impressionism.webp`,
    exampleImage: `https://picsum.photos/seed/impressionism/200/100`
  },
  {
    id: 'iron-pen-sketch',
    label: 'Iron Pen Sketch',
    label_vi: 'Phác thảo Bút sắt',
    folderId: 'fld_sketch',
    prompt: 'an intricate iron pen sketch, characterized by sharp, deliberate lines and cross-hatching for depth and shadow.',
    prompt_vi: 'một bản phác thảo bút sắt phức tạp, đặc trưng bởi các đường nét sắc sảo, có chủ ý và gạch chéo để tạo chiều sâu và bóng.',
    thumbnail: `${BUCKET_URL}/thumbnails/iron-pen-sketch.webp`,
    preview: `${BUCKET_URL}/previews/iron-pen-sketch.webp`,
    exampleImage: `https://picsum.photos/seed/iron-pen-sketch/200/100`
  },
  {
    id: 'lacquer-painting',
    label: 'Lacquer Painting',
    label_vi: 'Tranh Sơn mài',
    folderId: 'fld_vietnam',
    prompt: 'An artwork in the traditional Vietnamese lacquer painting style, featuring glossy surfaces, rich colors, and intricate mother-of-pearl inlay details.',
    prompt_vi: 'Một tác phẩm nghệ thuật theo phong cách tranh sơn mài truyền thống của Việt Nam, có bề mặt bóng, màu sắc phong phú và các chi tiết khảm xà cừ phức tạp.',
    thumbnail: `${BUCKET_URL}/thumbnails/lacquer-painting.webp`,
    preview: `${BUCKET_URL}/previews/lacquer-painting.webp`,
    exampleImage: `https://picsum.photos/seed/lacquer-painting/200/100`
  },
  {
    id: 'oil-painting',
    label: 'Oil Painting',
    label_vi: 'Tranh Sơn dầu',
    folderId: 'fld_oilpainting',
    prompt: 'an expressive oil painting with visible brushstrokes and rich textures.',
    prompt_vi: 'một bức tranh sơn dầu biểu cảm với các nét cọ có thể nhìn thấy và kết cấu phong phú.',
    thumbnail: `${BUCKET_URL}/thumbnails/oil-painting.webp`,
    preview: `${BUCKET_URL}/previews/oil-painting.webp`,
    exampleImage: `https://picsum.photos/seed/oil-painting/200/100`
  },
  {
    id: 'pixel-art',
    label: 'Pixel Art',
    label_vi: 'Nghệ thuật Pixel',
    folderId: 'fld_hoathinh',
    prompt: 'a retro pixel art style, reminiscent of 16-bit video games.',
    prompt_vi: 'một phong cách nghệ thuật pixel cổ điển, gợi nhớ đến các trò chơi điện tử 16-bit.',
    thumbnail: `${BUCKET_URL}/thumbnails/pixel-art.webp`,
    preview: `${BUCKET_URL}/previews/pixel-art.webp`,
    exampleImage: `https://picsum.photos/seed/pixel-art/200/100`
  },
  {
    id: 'sculpture',
    label: 'Sculpture',
    label_vi: 'Điêu khắc Đá',
    folderId: 'fld_dieukhac',
    prompt: 'as if it were a classical marble sculpture, with smooth textures and dramatic lighting.',
    prompt_vi: 'như thể nó là một tác phẩm điêu khắc bằng đá cẩm thạch cổ điển, with kết cấu mịn màng và ánh sáng đầy kịch tính.',
    thumbnail: `${BUCKET_URL}/thumbnails/sculpture.webp`,
    preview: `${BUCKET_URL}/previews/sculpture.webp`,
    exampleImage: `https://picsum.photos/seed/sculpture/200/100`
  },
  {
    id: 'studio-ghibli',
    label: 'Studio Ghibli Style',
    label_vi: 'Phong cách Ghibli',
    folderId: 'fld_hoathinh',
    prompt: 'In the whimsical and detailed animation style of Studio Ghibli, with a focus on nature and serene atmospheres.',
    prompt_vi: 'Theo phong cách hoạt hình hay thay đổi và chi tiết của Studio Ghibli, tập trung vào thiên nhiên và bầu không khí thanh bình.',
    thumbnail: `${BUCKET_URL}/thumbnails/studio-ghibli.webp`,
    preview: `${BUCKET_URL}/previews/studio-ghibli.webp`,
    exampleImage: `https://picsum.photos/seed/studio-ghibli/200/100`
  },
  {
    id: 'vietnamese-folk-animation',
    label: 'Vietnamese Folk Animation',
    label_vi: 'Hoạt hình Dân gian VN',
    folderId: 'fld_vietnam',
    prompt: 'An artwork in the style of traditional Vietnamese footer folk animation, characterized by simple, bold outlines, flat areas of color, and charming, stylized figures often depicting rural life and folklore.',
    prompt_vi: 'Một tác phẩm nghệ thuật theo phong cách hoạt hình dân gian truyền thống của Việt Nam, đặc trưng bởi các đường viền đơn giản, đậm nét, các mảng màu phẳng và các nhân vật cách điệu, duyên dáng thường mô tả cuộc sống nông thôn và văn hóa dân gian.',
    thumbnail: `${BUCKET_URL}/thumbnails/vietnamese-folk-animation.webp`,
    preview: `${BUCKET_URL}/previews/vietnamese-folk-animation.webp`,
    exampleImage: `https://picsum.photos/seed/vietnamese-folk-animation/200/100`
  },
  {
    id: 'watercolor',
    label: 'Watercolor',
    label_vi: 'Tranh Màu nước',
    folderId: 'fld_watercolor',
    prompt: 'a delicate watercolor painting with soft edges and transparent layers.',
    prompt_vi: 'một bức tranh màu nước tinh tế với các cạnh mềm mại và các lớp trong suốt.',
    thumbnail: `${BUCKET_URL}/thumbnails/watercolor.webp`,
    preview: `${BUCKET_URL}/previews/watercolor.webp`,
    exampleImage: `https://picsum.photos/seed/watercolor/200/100`
  }
];
